### PR TITLE
remove si.type checking when parsing swing tags

### PR DESCRIPTION
**Pull request by FounderSG**
this checking should not be there.

### CODE REVIEW

**Comment by strawmanbobi** [comment]
Dear,
Thank you very much for reviewing the code so carefully.
However, I don't think this change is necessary.
These 2 tags 'TAG_AC_SWING_1' and 'TAG_AC_SWING_2' just indicate how the functionality swing and wind direction is controled. Actually, they may be included in the binary code even if tag 'TAG_AC_SWING_INFO' does NOT indicate this air conditioner support normal swing. This is by some historical issue of the current binary codes.
So I prefer to keep the TAG_AC_SWING being parsed first and then parse 'TAG_AC_SWING_1 and 2' according to its value. in order to make the algorithm more compatible with all curent binaries.

Anyway, thanks again for your PR and careful code review. Please feel free to contact me if there is any more problem.

**Comment by FounderSG** [comment]
do you mean TAG_AC_SWING_1 and TAG_AC_SWING_2 is useless when SWING_TYPE_SWING_ONLY?
what's the difference between SWING_TYPE_SWING_ONLY and SWING_TYPE_NOT_SPECIFIED?
looks like both of them means no swing control.

**Comment by strawmanbobi** [comment]
Yes, according to the function get_supported_swing or the documentation, here swing type indicate both of swing and wind direction control support.
while swing_type == 2 it means this air conditioner only support swing (or not swing)
while swing_type == 3 it means this air conditioner support swing as well as fixed wind direction, here we can parse the specific wind direction values according to SWING_TAG (sorry for the not very precise use of wording 'swing' instead of 'wind_direction')
while swing_type == 0 it meas the SWING_TAG is not present in binary code.
And what's more, 1 is a preserved value of this tag.
Thanks //

**Comment by FounderSG** [comment]
Thanks for the clear explanation, the patch is indeed not necessary.

**Comment by strawmanbobi** [comment]
You are welcome. Please feel free to contact me if need any help.
And dont forget to star for this project (https://github.com/irext/irext) , if you feel helpful~
Thanks.

**Pull request closed without merging**
